name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Build for Windows
      run: |
        export GOOS=windows
        export GOARCH=amd64
        go build -ldflags="-s -w" -o release/helloworld.exe

    - name: Build for Linux
      run: |
        export GOOS=linux
        export GOARCH=amd64
        go build -ldflags="-s -w" -o release/helloworld

    - name: Build for macOS
      run: |
        export GOOS=darwin
        export GOARCH=amd64
        go build -ldflags="-s -w" -o release/helloworld

    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false

    - name: Upload release assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: release/helloworld*
        asset_name: helloworld_${{ env.GOOS }}_${{ env.GOARCH }}.zip
        asset_content_type: application/zip
