name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Build for Windows
      run: |
        export GOOS=windows
        export GOARCH=amd64
        go build -ldflags="-s -w" -o release/helloworld.exe

    - name: Build for Linux
      run: |
        export GOOS=linux
        export GOARCH=amd64
        go build -ldflags="-s -w" -o release/helloworld

    - name: Build for macOS
      run: |
        export GOOS=darwin
        export GOARCH=amd64
        go build -ldflags="-s -w" -o release/helloworld
